### ISSUE TITLE
AAwallet作成

### ISSUE THREAD

**Issue by ponponnsan** [ponponnsan/key3_hackathon_drive#4]

**Comment by cardene777** [comment]
- [viem astarZkatana](https://github.com/wagmi-dev/viem/blob/main/src/chains/definitions/astarZkatana.ts)
- [zerodevapp/sdk](https://github.com/zerodevapp/sdk/tree/5a5a821be8f3c46afb6f41e35dedc82a641f1f30)

**Comment by cardene777** [comment]
- [ ] ponさん宛に機能呼び出しのissue作成
